name = "us-politics-news-daily-rss-trigger"
main = "cloudflare/daily-rss-trigger.js"
compatibility_date = "2026-06-20"

[triggers]
crons = ["30 23 * * *", "35 23 * * 0", "40 23 28-31 * *", "45 23 * * *"]
