name: Weekly Publish
on:
  schedule:
    - cron: '35 23 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  delegate:
    uses: ./.github/workflows/publish-product.yml
    with:
      product_key: news
      report_type: weekly
    secrets: inherit
